version: "3"
services:
  mysql:
    image: mysql:8.0.3
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: letmein
      MYSQL_DATABASE: camunda
      MYSQL_USER: camunda_user
      MYSQL_PASSWORD: letmein

  camunda:
      build:
        context: .
      volumes:
        - "./src:/antifraud/src"
      ports:
        - 8080:8080
      depends_on:
        - mysql

