apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "worker.name" . }}
    helm.sh/chart: {{ include "worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BPM_ENGINE_URL
              value: {{ .Values.application.bpm_engine_url | quote }}
            - name: MONGO_HOST
              value: {{ .Values.mongo.host | quote }}
            - name: MONGO_PORT
              value: {{ .Values.mongo.port | quote }}
            - name: MONGO_USERNAME
              value: {{ .Values.mongo.username | quote }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: antifraud-mongodb
                  key: mongodb-root-password
            - name: MONGO_DBNAME
              value: {{ .Values.mongo.dbname | quote }}
          ports:
            - containerPort: 3000
              protocol: TCP
              name: app
          resources:
            requests:
              cpu: 10m
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
