apiVersion: v1
kind: Service
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    app: {{ include "worker.name" . }}
    app.kubernetes.io/name: {{ include "worker.name" . }}
    helm.sh/chart: {{ include "worker.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
