version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./src:/code/src"
      - "./views:/code/views"
      - "./dist:/code/dist"
    entrypoint: npm
    command: ["run", "dev-server"]
    env_file: .env

  static:
    build:
      context: .
      dockerfile: ./docker/static/Dockerfile
    volumes:
      - "./static:/code/static"
      - "./dist:/code/dist"
networks:
  default:
    external:
      name: antifraud_default

