defaults: &defaults
  working_directory: ~/workspace/repo
prod_repo: &prod_repo 289609572201.dkr.ecr.us-east-1.amazonaws.com/prod/labs-antifraud-storefront
machine_executor: &machine_executor
  machine: true
node_image: &node_image
  docker:
    - image: circleci/node:10.13-stretch-browsers-legacy
go_image: &go_image
  docker:
    - image: circleci/golang:1.11.2-stretch-browsers-legacy
install_awscli: &install_awscli
  run:
    name: Install AWS CLI
    command: sudo apt-get update && sudo apt-get install -y awscli
install_k8_client: &install_k8_client
  run:
    name: Install K8 Client
    command: |
      sudo apt-get update && sudo apt-get install -y apt-transport-https
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubectl
install_helm: &install_helm
  run:
    name: Install Helm
    command: |
      curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
      chmod 700 get_helm.sh
      ./get_helm.sh -v v2.11.0
      helm init --client-only
install_authenticator: &install_authenticator
  run:
    name: Install Authenticator
    command: go get -u -v github.com/kubernetes-sigs/aws-iam-authenticator/cmd/aws-iam-authenticator
setup_kubectl: &setup_kubectl
  run:
    name: Fetch Kubeconfig
    command: aws s3 cp "$KUBECONFIG" ~/.kube/config
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/workspace

version: 2
jobs:
  checkout:
    <<: *node_image
    steps:
      - checkout:
          path: ~/workspace/repo
      - persist_to_workspace:
          root: ~/workspace
          paths: repo/

  build-prod-image:
    <<: *defaults
    <<: *machine_executor
    environment:
      ECR_REPO: *prod_repo
    steps:
      - <<: *attach_workspace
      - run:
          name: Docker Build
          command: docker build -t prod/labs-antifraud-storefront:latest .
      - run:
          name: Tag Build
          command: docker tag prod/labs-antifraud-storefront:latest "$ECR_REPO":latest
      - run:
          name: Push Build
          command: |
            eval $(aws ecr get-login --no-include-email --region us-east-1)
            docker push "$ECR_REPO":latest

  deploy-prod:
    <<: *defaults
    <<: *go_image
    steps:
      - <<: *attach_workspace
      - <<: *install_awscli
      - <<: *install_k8_client
      - <<: *install_helm
      - <<: *install_authenticator
      - <<: *setup_kubectl
      - run:
          name: Upgrade helm package
          command: |
            KUBECONFIG=~/.kube/config helm upgrade --install storefront helm/storefront -f helm/prod-values.yaml --force --recreate-pods

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout
      - build-prod-image:
          requires:
            - checkout
          filters:
            branches:
              only: master
      - deploy-prod:
          context: k8-deployment
          requires:
            - build-prod-image
          filters:
            branches:
              only: master
