apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "storefront.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "storefront.name" . }}
    helm.sh/chart: {{ include "storefront.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "storefront.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "storefront.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BPM_ENGINE_URL
              value: {{ .Values.application.bpm_engine_url | quote }}
            - name: BPM_PROCESS_DEFINITION_KEY
              value: {{ .Values.application.bpm_process_definition_key | quote }}
            - name: MONGO_HOST
              value: {{ include "storefront.fullname" . }}-mongodb
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: {{ .Values.mongo.mongodbUsername }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.existingSecret }}
                  key: mongodb-root-password
            - name: MONGO_DBNAME
              value: {{ .Values.mongo.mongodbDatabase }}
          ports:
            - containerPort: 3000
              protocol: TCP
              name: app
          readinessProbe:
            httpGet:
              path: /api/ht/
              port: app
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /api/ht/
              port: app
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              cpu: 10m
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
