{{- if .Values.ingress.enabled -}}
{{- $fullName := include "storefront.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    app: {{ $fullName }}-ingress
    app.kubernetes.io/name: {{ include "storefront.name" . }}
    helm.sh/chart: {{ include "storefront.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
